type: object
properties:
  id:
    type: string
    description: A canonical ID that can be used to retrieve the Sunshine Conversations app.
    example: "5d8cff3cd55b040010928b5b"
  displayName:
    allOf:
      - $ref: "../schemas/displayName.yaml"
    description: The friendly name of the app.
    example: "My App"
  settings:
    $ref: "./appSettings.yaml"
  metadata:
    $ref: "./metadata.yaml"
