type: object
description: Customizable app settings.
properties:
  conversationRetentionSeconds:
    type: integer
    description: |
      Number of seconds of inactivity before a conversation’s messages 
      will be automatically deleted. See 
      [Conversation Retention Seconds](https://docs.smooch.io/rest/#conversation-retention-seconds)
      for more information.
    minimum: 0
  maskCreditCardNumbers:
    type: boolean
    description: |
      A boolean specifying whether credit card numbers should be masked 
      when sent through Sunshine Conversations.
  useAnimalNames:
    type: boolean
    description: |
      A boolean specifying whether animal names should be used for 
      unnamed users. See the 
      [user naming guide](https://docs.smooch.io/guide/receiving-messages/#message-author-name)
      for details.
  echoPostback:
    type: boolean
    description: |
      A boolean specifying whether a message should be added to the conversation 
      history when a postback button is clicked. See 
      [Echo Postbacks](https://docs.smooch.io/rest/#echo-postbacks)
      for more information.
  ignoreAutoConversationStart:
    type: boolean
    description: |
      A boolean specifying whether a non message event coming from a channel will 
      trigger a 
      [start conversation](https://docs.smooch.io/rest/#conversation-events)
      event and count as a monthly active user (MAU).
      <aside class="notice">Calling <code>startConversation()</code> (or equivalent) from the Android, 
      iOS or Web SDK will count as a MAU, regardless of the value of this setting.</aside>
  multiConvoEnabled:
    type: boolean
    description: |
      A boolean specifying whether users are allowed to be part of several conversations.
      Enabling `multiConvo` is **irreversible**.
  attachmentsAccess:
    type: string
    description: |
      A string specifying whether attachments should be stored in a publicly or privately accessible cloud storage.
      attachmentsAccess is set to public by default but can be modified to private.
      See <a href="https://docs.smooch.io/guide/private-attachments/">Private Attachments</a> for more information.
    example: public
  attachmentsTokenExpirationSeconds:
    type: string
    description: |
      Number of seconds representing the expiration time of the generated media tokens for private attachments. The JWT will be valid for 2 hours by default.
      See See <a href="https://docs.smooch.io/guide/private-attachments/">Private Attachments</a> for more information.
    example: 64028
