type: object
description: Response metadata.
properties:
  hasMore:
    type: boolean
    description: A flag that indicates if there are more records that can be fetched.
  afterCursor:
    type: string
    description: |
      A record id that can be used as a `page[after]` parameter in a new request to get the next page. 
      Not specified if there are no subsequent pages.
    example: "55c8d9758590aa1900b9b9f6"
  beforeCursor:
    type: string
    description: |
      A record id that can be used as a `page[before]` parameter in a new request to get the previous page. 
      Not specified if there are no previous pages.
    example: "55c8d9758590aa1900b9b9f6"
